# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Benchmark

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'example_config/**'
      - 'k8s_template/**'
      - 'changes/**'
      - 'licenses/**'
      - 'CHANGELOG.md'

jobs:
  Build-LoongCollector-Linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: [self-hosted, Linux, X64]
          - arch: arm64
            runner: [self-hosted, Linux, ARM64]
      fail-fast: false
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: false
  
      - name: Set custom submodule URL and fetch
        run: |
          SUBMODULE_PATH="core/_thirdparty/coolbpf"
          git config submodule.$SUBMODULE_PATH.url "https://github.com/aliyun/coolbpf.git"
          git submodule update --init
          cd $SUBMODULE_PATH
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Build linux/${{ matrix.arch }} image
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $REPO_OWNER --password-stdin
          docker build --tag ghcr.io/$REPO_OWNER/loongcollector:edge-linux-${{ matrix.arch }} \
              --file ./docker/Dockerfile_edge_linux .
          docker push ghcr.io/$REPO_OWNER/loongcollector:edge-linux-${{ matrix.arch }}

  Build-LoongCollector-Image:
    runs-on: ubuntu-latest
    needs: [ Build-LoongCollector-Linux ]
    steps:
      - name: Create and push manifest
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $REPO_OWNER --password-stdin
          docker manifest create ghcr.io/$REPO_OWNER/loongcollector:edge \
            --amend ghcr.io/$REPO_OWNER/loongcollector:edge-linux-amd64 \
            --amend ghcr.io/$REPO_OWNER/loongcollector:edge-linux-arm64
          docker manifest push ghcr.io/$REPO_OWNER/loongcollector:edge

  # Benchmark:
  #   runs-on: ${{ matrix.runner }}
  #   timeout-minutes: 60
  #   strategy:
  #     matrix:
  #       test-agent: 
  #         - "loongcollector-blackhole"
  #         - "loongcollector-spl-blackhole"
  #         - "filebeat-blackhole"
  #         - "fluentbit-blackhole"
  #         - "vector-blackhole"
  #         - "loongcollector-file"
  #         - "loongcollector-spl-file"
  #         - "loongcollector-cgo-file"
  #         - "filebeat-file"
  #         - "fluentbit-file"
  #         - "vector-file"
  #       python-version: [ 3.8 ]
  #       runner: [ ubuntu-latest ]
  #     fail-fast: false
  #   permissions:
  #     contents: write
  #     packages: read
  #   needs: [ Build-LoongCollector-Image ]
  #   steps:
  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.19.10

  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Check out code
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: false

  #     - name: Update Docker-compose to v2
  #       run: |
  #         sudo curl -SL https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  #         sudo chmod +x /usr/local/bin/docker-compose

  #     - name: Prepare test environment
  #       run: |
  #         pip3 install -r test/requirements.txt

  #     - name: Pull Docker image from GitHub Packages
  #       if: contains(matrix.test-agent, 'loongcollector')
  #       run: |
  #         REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
  #         echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $REPO_OWNER --password-stdin
  #         docker pull ghcr.io/$REPO_OWNER/loongcollector:edge
  #         docker tag ghcr.io/$REPO_OWNER/loongcollector:edge aliyun/loongcollector:0.0.1

  #     - name: Run benchmark for agent ${{ matrix.test-agent }}
  #       uses: nick-fields/retry@v3
  #       with:
  #         timeout_minutes: 10
  #         max_attempts: 3
  #         command: |
  #           set -ue
  #           ./scripts/e2e.sh benchmark performance "${{ matrix.test-agent }}"
  #           git stash
      
  #     - name: Upload benchmark result for agent ${{ matrix.test-agent }}
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: benchmark-results-${{ matrix.test-agent }}
  #         path: test/benchmark/report

  # result:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   needs: [ Benchmark ]
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: false

  #     - name: Download benchmark results
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: test/benchmark/report/
  #         merge-multiple: true

  #     - name: Display structure of downloaded files and merge
  #       run: |
  #         ls -R test/benchmark/report/
  #         ./scripts/benchmark_collect_result.sh
  #         ls -R test/benchmark/report/

  #     - name: Store benchmark result LoongCollector
  #       uses: benchmark-action/github-action-benchmark@v1
  #       with:
  #         name: benchmark
  #         tool: "customSmallerIsBetter"
  #         output-file-path: "test/benchmark/report/loongcollector_statistic_all.json"
  #         auto-push: false
  #         summary-always: true

  #     - name: Store benchmark result other agents
  #       run: |
  #         git checkout gh-pages
  #         mv test/benchmark/report/records_all.json dev/bench/records_all.js
  #         sed -i '1s/^\[/window.BENCHMARK_RECORDS = [/' dev/bench/records_all.js
  #         git add dev/bench/records_all.js
  #         last_commit_message=$(git log -1 --pretty=%B)
  #         git -c user.name=github-action-benchmark -c user.email=github@users.noreply.github.com commit --amend -m "$last_commit_message"

  #     - name: Push benchmark result
  #       run: git push 'https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/LoongCollector.git' gh-pages:gh-pages

  actions-timeline:
    needs: [Build-LoongCollector-Image]
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: Kesin11/actions-timeline@v2